# -*- coding: utf-8 -*-
"""ML Assignment 1_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQ1-gNZ4yQIxbV9HUbvbDMXIfnybkQAO
"""

import numpy as np
import pandas as pd

url = 'https://raw.githubusercontent.com/RealGagandeep/DataSet-for-ML/main/data/q4/q4x.dat'
data = pd.read_csv(url,sep = '  ')
arr0 = pd.DataFrame(data)
l = arr0.to_numpy()#******************************

m0 = np.mean(l[:,0])
m1 = np.mean(l[:,1])
std0 = np.std(l[:,0])
std1 = np.std(l[:,1])
m=[]
m.append(m0)
m.append(m1)

c0 = (l[:,0]-m0)/std0       # Normalized data setof all x values in 0th column
c1 = (l[:,1]-m1)/std1       # Normalized data setof all x values in 1th column
x = []
x.append(c0)
x.append(c1) #= (l-m)/np.std(l[:,0])#***************************
x = np.array(x).T           # Normalized data set of X
m=[]
m.append(np.mean(x[:,0]))
m.append(np.mean(x[:,1]))


url = 'https://raw.githubusercontent.com/RealGagandeep/DataSet-for-ML/main/data/q4/q4y.dat'
data = pd.read_csv(url)
arr1 = pd.DataFrame(data)
k = arr1.to_numpy()

y = []                            # Have data set of Y
for i in range(len(k)):           # Alaska = 0 ; Canada = 1
  if(k[i]=='Alaska'):
    y.append(0)
  if(k[i]=='Canada'):
    y.append(1)


def phif(y):                    # Returns the value of probability of y=1
  c = 0
  for i in range(len(y)):
    if(y[i]==1):
      c+=1
  return c/len(k)
phi = phif(y)

def meu(y,x,val):               # Returns 2D array of mean, for given case of y(y=0 OR y=1)
  c = 0
  sum0 = 0
  sum1 = 0
  for i in range(len(y)):
    if(y[i]==val):
      c+=1
      sum0 = sum0 + x[i,0]
      sum1 = sum1 + x[i,1]
  sum0 = sum0/c
  sum1 = sum1/c
  return [sum0,sum1]


def rowInc(meu0,x):             # Increases theno. of rows of the given matrix equal to x used in function 'sigma'
  l = []
  for i in range(len(x)):
    l.append(meu0)
  return l
m0 = meu(y,x,0)
m1 = meu(y,x,1)



x0 = x[:50]
x1 = x[50:]

def sigma(x,m):
  val = (x-rowInc(m,x)).T@(x-rowInc(m,x))/len(x)
  return val


print(f'mean of data of alaska is{np.mean(x0[:,0]),np.mean(x0[:,1])}, mean of data of canada is{np.mean(x1[:,0]),np.mean(x1[:,1])}\n\n')
print(f'the sigma0 (of 0 elements "alaska") of the data is:\n{sigma(x0,m0)}\n\nThe sigma1 (of 1 elements "canada") of the data is:\n{sigma(x1,m1)}\n\n\nThe Sigma_not of the data is: {sigma(x,m)}')
print(f'The mean m0 is {m0} and mean m1 is {m1}')

with open("result_4.txt", "a") as f:
  print(f'mean of data of alaska is{np.mean(x0[:,0]),np.mean(x0[:,1])}, mean of data of canada is{np.mean(x1[:,0]),np.mean(x1[:,1])}\n\n', file=f)
  print(f'the sigma0 (of 0 elements "alaska") of the data is:\n{sigma(x0,m0)}\n\nThe sigma1 (of 1 elements "canada") of the data is:\n{sigma(x1,m1)}\n\n\nThe Sigma_not of the data is: {sigma(x,m)}', file=f)
  print(f'The mean m0 is {m0} and mean m1 is {m1}', file=f)



# import matplotlib.pyplot as plt



# a=x0[:,0]
# b=x0[:,1]

# plt.scatter(a, b, c='green')

# a = x1[:,0]
# b = x1[:,1]

# plt.scatter(a, b, c='red')


# plt.show()

